server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
