server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  datasource:
    name: mydb
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
mybatis:
    mapper-locations: classpath:mappers/**/*Mapper.xml
    type-aliases-package: org.lk.springboot.demo.domain.model
    config-location: classpath:mybatis-config.xml
pagehelper:
  auto-dialect: true
  reasonable: true