create table user_info(
  ID BIGINT AUTO_INCREMENT COMMENT '主键ID',
  CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
  LAST_UPDATE_TEIM DATETIME COMMENT '最后更新时间',
  USERNAME VARCHAR(32) NOT NULL COMMENT '用户名',
  PASSWORD VARCHAR(64) NOT NULL COMMENT '密码',
  SALT VARCHAR(32) NOT NULL COMMENT '盐',
  ADDRESS VARCHAR(64) COMMENT '地址',
  PHONT VARCHAR(20) COMMENT '电话',
  PRIMARY KEY (ID)
);

create table goods(
  ID BIGINT AUTO_INCREMENT COMMENT '主键ID',
  CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
  LAST_UPDATE_TEIM DATETIME COMMENT '最后更新时间',
  NAME VARCHAR(32) NOT NULL COMMENT '商品名称',
  PRICE DECIMAL(10,2) NOT NULL COMMENT '商品价格',
  ICON VARCHAR(200) COMMENT '商品图片',
  PRIMARY KEY (ID)
)